# Generated by Django 3.2 on 2023-01-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(db_column='team', max_length=255)),
                ('date', models.DateField(db_column='date')),
            ],
            options={
                'db_table': 'team_record',
                'managed': False,
            },
        ),
    ]
