# Generated by Django 3.2 on 2023-01-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_column='category', max_length=255)),
                ('preference', models.IntegerField(db_column='preference', max_length=11)),
                ('user_id', models.CharField(db_column='user_id', max_length=255)),
            ],
            options={
                'db_table': 'food_preference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('email_id', models.CharField(db_column='email_id', max_length=255)),
                ('password', models.CharField(db_column='password', max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
