# Generated by Django 3.2 on 2023-01-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230115_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='MustFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('category', models.CharField(db_column='category', max_length=255)),
                ('preference', models.IntegerField(db_column='preference')),
            ],
            options={
                'db_table': 'must_food',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(db_column='department', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(db_column='phone', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
